---
name: POC katalon
on:
  workflow_dispatch:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Katalon Studio Github Action
        uses: katalon-studio/katalon-studio-github-action@v2
        with:
          version: '8.6.8'
          projectPath: '${{ github.workspace }}'
          args: '-noSplash -retry=0 -browserType=Chrome  -statusDelay=15 -testSuitePath="Test Suites/LS4/LSX4_Deployment_Smoke" -apiKey=694f1d60-c2fa-438f-a734-2cd8eb1e7cf1 -orgID=144578--config -webui.autoUpdateDrivers=true'
