---
name: POC katalon
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Katalon Studio Github Action
        uses: katalon-studio/katalon-studio-github-action@v2
        with:
          version: 8.5.5
          projectPath: ${{ github.workspace }}
          run: katalonc -noSplash -runMode=console
            -projectPath="git\Katalon_POC\Katalon_POC.prj" -retry=0
            -testSuitePath="Test Suites/POCcollection" -browserType="Chrome"
            -executionProfile="default"
            -apiKey= "694f1d60-c2fa-438f-a734-2cd8eb1e7cf1".API key --config
            -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY
            -proxy.system.applyToDesiredCapabilities=true
            -webui.autoUpdateDrivers=true
