---
name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v
      - name: Katalon Studio Github Action
        uses: katalon-studio/katalon-studio-github-action@v
        with:
          version: 7.5.5
          projectPath: ${{ github.workspace }}
          args: katalonc -noSplash -runMode=console
            -projectPath="git\Katalon_POC\Katalon_POC.prj" -retry=0
            -testSuitePath="Test Suites/POCcollection" -browserType="Chrome"
            -executionProfile="default"
            -apiKey="433e8342-0c21-4fc7-b8d7-b4beacbb9a85" --config
            -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY
            -proxy.system.applyToDesiredCapabilities=true
            -webui.autoUpdateDrivers=true
